const { contextBridge, ipcRenderer, webUtils } = require('electron');

const UPTIME_IPC_VERSION = 1;
const DATABASE_MANAGER_IPC_VERSION = 1;
const DATABASE_MANAGER_EVENT_VERSION = 1;

// Sandboxed Electron preloads cannot require local application modules.
function unwrapUptimeIpc(response) {
  if (!response || response.uptimeIpcVersion !== UPTIME_IPC_VERSION || typeof response.ok !== 'boolean') {
    const error = new Error('The Uptime service returned an unsupported response.');
    error.code = 'UPTIME_IPC_RESPONSE_INVALID';
    error.category = 'ipc';
    throw error;
  }
  if (response.ok) return response.value;
  const error = new Error(String(response.error?.message || 'Could not complete the Uptime operation.'));
  error.code = String(response.error?.code || 'UPTIME_OPERATION_FAILED');
  error.category = String(response.error?.category || 'uptime');
  throw error;
}

async function invokeUptime(channel, ...args) {
  return unwrapUptimeIpc(await ipcRenderer.invoke(channel, ...args));
}

function unwrapDatabaseManagerIpc(response) {
  if (!response || response.databaseManagerIpcVersion !== DATABASE_MANAGER_IPC_VERSION || typeof response.ok !== 'boolean') {
    const error = new Error('The Database Manager returned an unsupported response.');
    error.code = 'DATABASE_MANAGER_IPC_RESPONSE_INVALID';
    throw error;
  }
  if (response.ok) return response.value;
  const error = new Error(String(response.error?.safeMessage || 'The Database Manager operation failed.'));
  error.code = String(response.error?.code || 'DATABASE_MANAGER_OPERATION_FAILED');
  error.category = String(response.error?.category || 'database-manager');
  error.retryable = Boolean(response.error?.retryable);
  error.details = response.error?.details && typeof response.error.details === 'object' ? response.error.details : {};
  throw error;
}

async function invokeDatabaseManager(channel, ...args) {
  return unwrapDatabaseManagerIpc(await ipcRenderer.invoke(channel, ...args));
}

contextBridge.exposeInMainWorld('deployerx', {
  getAppMetadata: () => ipcRenderer.invoke('app:metadata'),
  readClipboard: () => ipcRenderer.sendSync('clipboard:read-sync'),
  writeClipboard: (text) => ipcRenderer.sendSync('clipboard:write-sync', String(text ?? '')),
  getUpdateState: () => ipcRenderer.invoke('app:update-state'),
  checkForUpdates: () => ipcRenderer.invoke('app:update-check'),
  openReleasesPage: () => ipcRenderer.invoke('app:update-open-releases'),
  openExternalUrl: (url) => ipcRenderer.invoke('app:open-external-url', String(url || '')),
  installUpdate: () => ipcRenderer.invoke('app:update-install'),
  getSetup: () => ipcRenderer.invoke('setup:get'),
  getTheme: () => ipcRenderer.sendSync('theme:get-sync'),
  setTheme: (themeId) => ipcRenderer.invoke('theme:set', themeId),
  getMcpIntegration: () => ipcRenderer.invoke('mcp-integration:get'),
  startMcpIntegration: (payload) => ipcRenderer.invoke('mcp-integration:start', payload),
  stopMcpIntegration: () => ipcRenderer.invoke('mcp-integration:stop'),
  rotateMcpToken: () => ipcRenderer.invoke('mcp-integration:rotate-token'),
  testMcpIntegration: () => ipcRenderer.invoke('mcp-integration:test'),
  setSetupMode: (mode) => ipcRenderer.invoke('setup:setMode', mode),
  selectFirebaseConfig: () => ipcRenderer.invoke('setup:select-firebase-config'),
  register: (payload) => ipcRenderer.invoke('auth:register', payload),
  login: (payload) => ipcRenderer.invoke('auth:login', payload),
  loginWithGoogle: () => ipcRenderer.invoke('auth:google'),
  forgotPassword: (payload) => ipcRenderer.invoke('auth:forgotPassword', payload),
  changePassword: (payload) => ipcRenderer.invoke('auth:changePassword', payload),
  resendVerification: () => ipcRenderer.invoke('auth:resendVerification'),
  logout: () => ipcRenderer.invoke('auth:logout'),
  authSession: () => ipcRenderer.invoke('auth:session'),
  listTeams: () => ipcRenderer.invoke('teams:list'),
  createTeam: (payload) => ipcRenderer.invoke('teams:create', payload),
  switchTeam: (teamId) => ipcRenderer.invoke('teams:switch', teamId),
  inviteTeamMember: (payload) => ipcRenderer.invoke('teams:invite', payload),
  revokeTeamInvite: (payload) => ipcRenderer.invoke('teams:revokeInvite', payload),
  acceptTeamInvite: (payload) => ipcRenderer.invoke('teams:acceptInvite', payload),
  removeTeamMember: (payload) => ipcRenderer.invoke('teams:removeMember', payload),
  deleteTeam: (payload) => ipcRenderer.invoke('teams:delete', payload),
  importLocalToCloud: () => ipcRenderer.invoke('cloud:import-local'),
  listProjects: () => ipcRenderer.invoke('projects:list'),
  saveProject: (project) => ipcRenderer.invoke('projects:save', project),
  deleteProject: (id) => ipcRenderer.invoke('projects:delete', id),
  exportProjects: (projectIds) => ipcRenderer.invoke('projects:export', projectIds),
  importProjects: () => ipcRenderer.invoke('projects:import'),
  startRdp: (payload) => ipcRenderer.invoke('rdp:start', payload),
  loadRdpWasm: () => ipcRenderer.invoke('rdp:wasm'),
  stopRdp: (sessionId) => ipcRenderer.invoke('rdp:stop', sessionId),
  setRdpFullscreen: (payload) => ipcRenderer.invoke('rdp:fullscreen', payload),
  exportAccount: () => ipcRenderer.invoke('account:export'),
  importAccount: () => ipcRenderer.invoke('account:import'),
  listBackupSecrets: () => ipcRenderer.invoke('backup:secrets:list'),
  createBackupSecret: (payload) => ipcRenderer.invoke('backup:secrets:create', payload),
  rotateBackupSecret: (payload) => ipcRenderer.invoke('backup:secrets:rotate', payload),
  deleteBackupSecret: (payload) => ipcRenderer.invoke('backup:secrets:delete', payload),
  listDatabaseProfiles: (options = {}) => invokeDatabaseManager('database-manager:profiles:list', options),
  getDatabaseProfile: (id) => invokeDatabaseManager('database-manager:profiles:get', { id }),
  createDatabaseProfile: (payload) => invokeDatabaseManager('database-manager:profiles:create', payload),
  updateDatabaseProfile: (id, revision, profile, cloudRevision = null) => invokeDatabaseManager('database-manager:profiles:update', { id, revision, profile, cloudRevision }),
  deleteDatabaseProfile: (id, revision, cloudRevision = null) => invokeDatabaseManager('database-manager:profiles:delete', { id, revision, cloudRevision }),
  resolveDatabaseProfileCloudConflict: (id, strategy) => invokeDatabaseManager('database-manager:profiles:resolve-cloud-conflict', { id, strategy }),
  testDatabaseProfile: (id) => invokeDatabaseManager('database-manager:connections:test', { id }),
  openDatabaseConnection: (id) => invokeDatabaseManager('database-manager:connections:open', { id }),
  closeDatabaseConnection: (id) => invokeDatabaseManager('database-manager:connections:close', { id }),
  openDatabaseAccess: (profileId) => invokeDatabaseManager('database-manager:access:open', { profileId }),
  getDatabaseConnectionStatus: (id) => invokeDatabaseManager('database-manager:connections:status', { id }),
  listDatabaseConnectionStatuses: () => invokeDatabaseManager('database-manager:connections:list-status'),
  bindDatabaseProfileLocalResource: (id) => invokeDatabaseManager('database-manager:local-resources:bind', { id }),
  prepareDatabaseProfileBackup: (id) => invokeDatabaseManager('database-manager:backup:prepare', { id }),
  executeDatabaseQuery: (payload) => invokeDatabaseManager('database-manager:queries:execute', payload),
  cancelDatabaseQuery: (requestId) => invokeDatabaseManager('database-manager:queries:cancel', { requestId }),
  explainDatabaseQuery: (payload) => invokeDatabaseManager('database-manager:explain:execute', payload),
  cancelDatabaseExplain: (requestId) => invokeDatabaseManager('database-manager:explain:cancel', { requestId }),
  executeDatabaseTransfer: (payload) => invokeDatabaseManager('database-manager:transfer:execute', payload),
  mutateDatabaseRows: (payload) => invokeDatabaseManager('database-manager:rows:mutate', payload),
  loadDatabaseSchema: (payload) => invokeDatabaseManager('database-manager:schema:load', payload),
  cancelDatabaseSchema: (requestId) => invokeDatabaseManager('database-manager:schema:cancel', { requestId }),
  getDatabaseSchemaCapabilities: (profileId) => invokeDatabaseManager('database-manager:schema:capabilities', { profileId }),
  executeDatabaseSchemaAction: (payload) => invokeDatabaseManager('database-manager:schema:execute', payload),
  getDatabasePrincipalCapabilities: (profileId) => invokeDatabaseManager('database-manager:principals:capabilities', { profileId }),
  listDatabasePrincipals: (profileId) => invokeDatabaseManager('database-manager:principals:list', { profileId }),
  inspectDatabasePrincipal: (payload) => invokeDatabaseManager('database-manager:principals:inspect', payload),
  executeDatabasePrincipalAction: (payload) => invokeDatabaseManager('database-manager:principals:execute', payload),
  listDatabaseSavedQueries: (options = {}) => invokeDatabaseManager('database-manager:saved-queries:list', options),
  createDatabaseSavedQuery: (payload) => invokeDatabaseManager('database-manager:saved-queries:create', payload),
  updateDatabaseSavedQuery: (id, revision, savedQuery) => invokeDatabaseManager('database-manager:saved-queries:update', { id, revision, savedQuery }),
  deleteDatabaseSavedQuery: (id, revision) => invokeDatabaseManager('database-manager:saved-queries:delete', { id, revision }),
  listDatabaseQueryHistory: (options = {}) => invokeDatabaseManager('database-manager:history:list', options),
  clearDatabaseQueryHistory: (options = {}) => invokeDatabaseManager('database-manager:history:clear', options),
  listDatabaseNotebooks: (options = {}) => invokeDatabaseManager('database-manager:notebooks:list', options),
  getDatabaseNotebook: (id) => invokeDatabaseManager('database-manager:notebooks:get', { id }),
  createDatabaseNotebook: (payload) => invokeDatabaseManager('database-manager:notebooks:create', payload),
  updateDatabaseNotebook: (id, revision, notebook) => invokeDatabaseManager('database-manager:notebooks:update', { id, revision, notebook }),
  deleteDatabaseNotebook: (id, revision) => invokeDatabaseManager('database-manager:notebooks:delete', { id, revision }),
  listDatabaseTasks: (options = {}) => invokeDatabaseManager('database-manager:tasks:list', options),
  getDatabaseTask: (id) => invokeDatabaseManager('database-manager:tasks:get', { id }),
  cancelDatabaseTask: (id) => invokeDatabaseManager('database-manager:tasks:cancel', { id }),
  listDatabaseOperationalLogs: (options = {}) => invokeDatabaseManager('database-manager:logs:list', options),
  serializeDatabaseQueryResults: (payload) => invokeDatabaseManager('database-manager:results:serialize', payload),
  exportDatabaseQueryResults: (payload) => invokeDatabaseManager('database-manager:results:export', payload),
  exportDatabaseQuery: (payload) => invokeDatabaseManager('database-manager:results:export-query', payload),
  cancelDatabaseQueryExport: (requestId) => invokeDatabaseManager('database-manager:results:cancel-export', { requestId }),
  listDatabasePlugins: () => invokeDatabaseManager('database-manager:plugins:list'),
  refreshDatabasePlugins: () => invokeDatabaseManager('database-manager:plugins:refresh'),
  recheckDatabasePluginRequirements: () => invokeDatabaseManager('database-manager:plugins:requirements:refresh'),
  installDatabasePlugin: (pluginId, version) => invokeDatabaseManager('database-manager:plugins:install', { pluginId, version }),
  checkDatabasePluginHealth: (pluginId) => invokeDatabaseManager('database-manager:plugins:health', { pluginId }),
  enableDatabasePlugin: (pluginId) => invokeDatabaseManager('database-manager:plugins:enable', { pluginId }),
  disableDatabasePlugin: (pluginId) => invokeDatabaseManager('database-manager:plugins:disable', { pluginId }),
  removeDatabasePlugin: (pluginId) => invokeDatabaseManager('database-manager:plugins:remove', { pluginId }),
  listBackupAuditEvents: (payload) => ipcRenderer.invoke('backup:audit:list', payload),
  verifyBackupAudit: () => ipcRenderer.invoke('backup:audit:verify'),
  listBackupLocalConnections: () => ipcRenderer.invoke('backup:connections:local:list'),
  ensureBackupLocalConnection: () => ipcRenderer.invoke('backup:connections:local:ensure'),
  testBackupLocalConnection: (id) => ipcRenderer.invoke('backup:connections:local:test', { id }),
  browseBackupLocalConnection: (id, payload = {}) => ipcRenderer.invoke('backup:connections:local:browse', { id, ...payload }),
  listBackupSshConnections: () => ipcRenderer.invoke('backup:connections:ssh:list'),
  scanBackupSshHostKey: (payload) => ipcRenderer.invoke('backup:connections:ssh:scan-host-key', payload),
  createBackupSshConnection: (payload) => ipcRenderer.invoke('backup:connections:ssh:create', payload),
  testBackupSshConnection: (id) => ipcRenderer.invoke('backup:connections:ssh:test', { id }),
  browseBackupSshConnection: (id, payload = {}) => ipcRenderer.invoke('backup:connections:ssh:browse', { id, ...payload }),
  listBackupMysqlConnections: () => ipcRenderer.invoke('backup:connections:mysql:list'),
  createBackupMysqlConnection: (payload) => ipcRenderer.invoke('backup:connections:mysql:create', payload),
  testBackupMysqlConnection: (id) => ipcRenderer.invoke('backup:connections:mysql:test', { id }),
  discoverBackupMysqlDatabases: (id, payload = {}) => ipcRenderer.invoke('backup:connections:mysql:discover', { id, ...payload }),
  listBackupMariadbConnections: () => ipcRenderer.invoke('backup:connections:mariadb:list'),
  createBackupMariadbConnection: (payload) => ipcRenderer.invoke('backup:connections:mariadb:create', payload),
  testBackupMariadbConnection: (id) => ipcRenderer.invoke('backup:connections:mariadb:test', { id }),
  discoverBackupMariadbDatabases: (id, payload = {}) => ipcRenderer.invoke('backup:connections:mariadb:discover', { id, ...payload }),
  listBackupPostgresqlConnections: () => ipcRenderer.invoke('backup:connections:postgresql:list'),
  createBackupPostgresqlConnection: (payload) => ipcRenderer.invoke('backup:connections:postgresql:create', payload),
  testBackupPostgresqlConnection: (id) => ipcRenderer.invoke('backup:connections:postgresql:test', { id }),
  discoverBackupPostgresqlDatabases: (id, payload = {}) => ipcRenderer.invoke('backup:connections:postgresql:discover', { id, ...payload }),
  listBackupSqlServerConnections: () => ipcRenderer.invoke('backup:connections:sqlserver:list'),
  createBackupSqlServerConnection: (payload) => ipcRenderer.invoke('backup:connections:sqlserver:create', payload),
  testBackupSqlServerConnection: (id) => ipcRenderer.invoke('backup:connections:sqlserver:test', { id }),
  discoverBackupSqlServerDatabases: (id, payload = {}) => ipcRenderer.invoke('backup:connections:sqlserver:discover', { id, ...payload }),
  listBackupOracleConnections: () => ipcRenderer.invoke('backup:connections:oracle:list'),
  createBackupOracleConnection: (payload) => ipcRenderer.invoke('backup:connections:oracle:create', payload),
  testBackupOracleConnection: (id) => ipcRenderer.invoke('backup:connections:oracle:test', { id }),
  discoverBackupOracleDatabases: (id, payload = {}) => ipcRenderer.invoke('backup:connections:oracle:discover', { id, ...payload }),
  listBackupMongoDbConnections: () => ipcRenderer.invoke('backup:connections:mongodb:list'),
  createBackupMongoDbConnection: (payload) => ipcRenderer.invoke('backup:connections:mongodb:create', payload),
  testBackupMongoDbConnection: (id) => ipcRenderer.invoke('backup:connections:mongodb:test', { id }),
  discoverBackupMongoDbDatabases: (id, payload = {}) => ipcRenderer.invoke('backup:connections:mongodb:discover', { id, ...payload }),
  listBackupRedisConnections: () => ipcRenderer.invoke('backup:connections:redis:list'),
  createBackupRedisConnection: (payload) => ipcRenderer.invoke('backup:connections:redis:create', payload),
  testBackupRedisConnection: (id) => ipcRenderer.invoke('backup:connections:redis:test', { id }),
  discoverBackupRedisDatabases: (id) => ipcRenderer.invoke('backup:connections:redis:discover', { id }),
  listBackupNeo4jConnections: () => ipcRenderer.invoke('backup:connections:neo4j:list'),
  createBackupNeo4jConnection: (payload) => ipcRenderer.invoke('backup:connections:neo4j:create', payload),
  testBackupNeo4jConnection: (id) => ipcRenderer.invoke('backup:connections:neo4j:test', { id }),
  discoverBackupNeo4jResources: (id, kind = 'all') => ipcRenderer.invoke('backup:connections:neo4j:discover', { id, kind }),
  listBackupClickHouseConnections: () => ipcRenderer.invoke('backup:connections:clickhouse:list'),
  createBackupClickHouseConnection: (payload) => ipcRenderer.invoke('backup:connections:clickhouse:create', payload),
  testBackupClickHouseConnection: (id) => ipcRenderer.invoke('backup:connections:clickhouse:test', { id }),
  discoverBackupClickHouseResources: (id, kind = 'all') => ipcRenderer.invoke('backup:connections:clickhouse:discover', { id, kind }),
  listBackupCockroachDbConnections: () => ipcRenderer.invoke('backup:connections:cockroachdb:list'),
  createBackupCockroachDbConnection: (payload) => ipcRenderer.invoke('backup:connections:cockroachdb:create', payload),
  testBackupCockroachDbConnection: (id) => ipcRenderer.invoke('backup:connections:cockroachdb:test', { id }),
  discoverBackupCockroachDbResources: (id, kind = 'all') => ipcRenderer.invoke('backup:connections:cockroachdb:discover', { id, kind }),
  approveBackupCockroachDbDestination: (id, payload) => ipcRenderer.invoke('backup:connections:cockroachdb:approve-destination', { id, ...payload }),
  previewBackupCockroachDbSchedule: (payload) => ipcRenderer.invoke('backup:cockroachdb-schedules:plan', payload),
  createBackupCockroachDbSchedule: (payload) => ipcRenderer.invoke('backup:cockroachdb-schedules:create', payload),
  listBackupCockroachDbSchedules: () => ipcRenderer.invoke('backup:cockroachdb-schedules:list'),
  reconcileBackupCockroachDbSchedule: (jobId) => ipcRenderer.invoke('backup:cockroachdb-schedules:reconcile', { jobId }),
  pauseBackupCockroachDbSchedule: (jobId) => ipcRenderer.invoke('backup:cockroachdb-schedules:pause', { jobId }),
  resumeBackupCockroachDbSchedule: (jobId) => ipcRenderer.invoke('backup:cockroachdb-schedules:resume', { jobId }),
  previewBackupCockroachDbRetention: (payload) => ipcRenderer.invoke('backup:cockroachdb-retention:preview', payload),
  executeBackupCockroachDbRetention: (payload) => ipcRenderer.invoke('backup:cockroachdb-retention:execute', payload),
  previewBackupCockroachDbRestore: (payload) => ipcRenderer.invoke('backup:cockroachdb-restores:preview', payload),
  listBackupCockroachDbRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:cockroachdb-restores:list', payload),
  startBackupCockroachDbRestore: (payload) => ipcRenderer.invoke('backup:cockroachdb-restores:start', payload),
  waitBackupCockroachDbRestore: (restoreRunId) => ipcRenderer.invoke('backup:cockroachdb-restores:wait', { restoreRunId }),
  pauseBackupCockroachDbRestore: (restoreRunId) => ipcRenderer.invoke('backup:cockroachdb-restores:pause', { restoreRunId }),
  resumeBackupCockroachDbRestore: (restoreRunId) => ipcRenderer.invoke('backup:cockroachdb-restores:resume', { restoreRunId }),
  cancelBackupCockroachDbRestore: (restoreRunId) => ipcRenderer.invoke('backup:cockroachdb-restores:cancel', { restoreRunId }),
  listBackupCockroachDbVerificationRuns: (payload = {}) => ipcRenderer.invoke('backup:cockroachdb-verifications:list', payload),
  startBackupCockroachDbVerification: (payload) => ipcRenderer.invoke('backup:cockroachdb-verifications:start', payload),
  waitBackupCockroachDbVerification: (verificationRunId) => ipcRenderer.invoke('backup:cockroachdb-verifications:wait', { verificationRunId }),
  cancelBackupCockroachDbVerification: (verificationRunId) => ipcRenderer.invoke('backup:cockroachdb-verifications:cancel', { verificationRunId }),
  listBackupInfluxDbConnections: () => ipcRenderer.invoke('backup:connections:influxdb:list'),
  createBackupInfluxDbConnection: (payload) => ipcRenderer.invoke('backup:connections:influxdb:create', payload),
  testBackupInfluxDbConnection: (id) => ipcRenderer.invoke('backup:connections:influxdb:test', { id }),
  discoverBackupInfluxDbResources: (id, kind = 'all') => ipcRenderer.invoke('backup:connections:influxdb:discover', { id, kind }),
  listBackupInfluxDb3EnterpriseConnections: () => ipcRenderer.invoke('backup:connections:influxdb3-enterprise:list'),
  createBackupInfluxDb3EnterpriseConnection: (payload) => ipcRenderer.invoke('backup:connections:influxdb3-enterprise:create', payload),
  testBackupInfluxDb3EnterpriseConnection: (id) => ipcRenderer.invoke('backup:connections:influxdb3-enterprise:test', { id }),
  discoverBackupInfluxDb3EnterpriseResources: (id, kind = 'all') => ipcRenderer.invoke('backup:connections:influxdb3-enterprise:discover', { id, kind }),
  previewBackupInfluxDb3EnterpriseRestore: (payload) => ipcRenderer.invoke('backup:influxdb3-enterprise-restores:preview', payload),
  listBackupInfluxDb3EnterpriseRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:influxdb3-enterprise-restores:list', payload),
  startBackupInfluxDb3EnterpriseRestore: (payload) => ipcRenderer.invoke('backup:influxdb3-enterprise-restores:start', payload),
  waitBackupInfluxDb3EnterpriseRestore: (restoreRunId) => ipcRenderer.invoke('backup:influxdb3-enterprise-restores:wait', { restoreRunId }),
  cancelBackupInfluxDb3EnterpriseRestore: (restoreRunId) => ipcRenderer.invoke('backup:influxdb3-enterprise-restores:cancel', { restoreRunId }),
  previewBackupInfluxDb3EnterpriseRetention: (payload) => ipcRenderer.invoke('backup:influxdb3-enterprise-retention:preview', payload),
  executeBackupInfluxDb3EnterpriseRetention: (payload) => ipcRenderer.invoke('backup:influxdb3-enterprise-retention:execute', payload),
  listBackupInfluxDb3EnterpriseVerificationRuns: (payload = {}) => ipcRenderer.invoke('backup:influxdb3-enterprise-verifications:list', payload),
  startBackupInfluxDb3EnterpriseVerification: (payload) => ipcRenderer.invoke('backup:influxdb3-enterprise-verifications:start', payload),
  waitBackupInfluxDb3EnterpriseVerification: (verificationRunId) => ipcRenderer.invoke('backup:influxdb3-enterprise-verifications:wait', { verificationRunId }),
  cancelBackupInfluxDb3EnterpriseVerification: (verificationRunId) => ipcRenderer.invoke('backup:influxdb3-enterprise-verifications:cancel', { verificationRunId }),
  planBackupInfluxDb3EnterpriseLegacyRetention: (recoveryPointId, repositoryId) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-retention:plan', { recoveryPointId, repositoryId }),
  executeBackupInfluxDb3EnterpriseLegacyRetention: (recoveryPointId, repositoryId, planId) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-retention:execute', { recoveryPointId, repositoryId, planId }),
  previewBackupInfluxDb3EnterpriseLegacyRestore: (payload) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-restores:preview', payload),
  listBackupInfluxDb3EnterpriseLegacyRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-restores:list', payload),
  startBackupInfluxDb3EnterpriseLegacyRestore: (payload) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-restores:start', payload),
  waitBackupInfluxDb3EnterpriseLegacyRestore: (restoreRunId) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-restores:wait', { restoreRunId }),
  cancelBackupInfluxDb3EnterpriseLegacyRestore: (restoreRunId) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-restores:cancel', { restoreRunId }),
  listBackupInfluxDb3EnterpriseLegacyVerificationRuns: (payload = {}) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-verifications:list', payload),
  startBackupInfluxDb3EnterpriseLegacyVerification: (payload) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-verifications:start', payload),
  waitBackupInfluxDb3EnterpriseLegacyVerification: (verificationRunId) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-verifications:wait', { verificationRunId }),
  cancelBackupInfluxDb3EnterpriseLegacyVerification: (verificationRunId) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-verifications:cancel', { verificationRunId }),
  listBackupInfluxDb3EnterpriseLegacyStopBindings: () => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-stop-bindings:list'),
  createBackupInfluxDb3EnterpriseLegacyStopBinding: (payload) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-stop-bindings:create', payload),
  removeBackupInfluxDb3EnterpriseLegacyStopBinding: (bindingId, expectedRevision) => ipcRenderer.invoke('backup:influxdb3-enterprise-legacy-stop-bindings:remove', { bindingId, expectedRevision }),
  listBackupInfluxDb3CoreConnections: () => ipcRenderer.invoke('backup:connections:influxdb3-core:list'),
  createBackupInfluxDb3CoreConnection: (payload) => ipcRenderer.invoke('backup:connections:influxdb3-core:create', payload),
  testBackupInfluxDb3CoreConnection: (id) => ipcRenderer.invoke('backup:connections:influxdb3-core:test', { id }),
  discoverBackupInfluxDb3CoreResources: (id, kind = 'all') => ipcRenderer.invoke('backup:connections:influxdb3-core:discover', { id, kind }),
  previewBackupInfluxDb3CoreRestore: (payload) => ipcRenderer.invoke('backup:influxdb3-core-restores:preview', payload),
  listBackupInfluxDb3CoreRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:influxdb3-core-restores:list', payload),
  startBackupInfluxDb3CoreRestore: (payload) => ipcRenderer.invoke('backup:influxdb3-core-restores:start', payload),
  waitBackupInfluxDb3CoreRestore: (restoreRunId) => ipcRenderer.invoke('backup:influxdb3-core-restores:wait', { restoreRunId }),
  cancelBackupInfluxDb3CoreRestore: (restoreRunId) => ipcRenderer.invoke('backup:influxdb3-core-restores:cancel', { restoreRunId }),
  listBackupInfluxDb3CoreVerificationRuns: (payload = {}) => ipcRenderer.invoke('backup:influxdb3-core-verifications:list', payload),
  startBackupInfluxDb3CoreVerification: (payload) => ipcRenderer.invoke('backup:influxdb3-core-verifications:start', payload),
  waitBackupInfluxDb3CoreVerification: (verificationRunId) => ipcRenderer.invoke('backup:influxdb3-core-verifications:wait', { verificationRunId }),
  cancelBackupInfluxDb3CoreVerification: (verificationRunId) => ipcRenderer.invoke('backup:influxdb3-core-verifications:cancel', { verificationRunId }),
  previewBackupInfluxDbRestore: (payload) => ipcRenderer.invoke('backup:influxdb-restores:preview', payload),
  listBackupInfluxDbRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:influxdb-restores:list', payload),
  startBackupInfluxDbRestore: (payload) => ipcRenderer.invoke('backup:influxdb-restores:start', payload),
  waitBackupInfluxDbRestore: (restoreRunId) => ipcRenderer.invoke('backup:influxdb-restores:wait', { restoreRunId }),
  cancelBackupInfluxDbRestore: (restoreRunId) => ipcRenderer.invoke('backup:influxdb-restores:cancel', { restoreRunId }),
  listBackupInfluxDbVerificationRuns: (payload = {}) => ipcRenderer.invoke('backup:influxdb-verifications:list', payload),
  startBackupInfluxDbVerification: (payload) => ipcRenderer.invoke('backup:influxdb-verifications:start', payload),
  waitBackupInfluxDbVerification: (verificationRunId) => ipcRenderer.invoke('backup:influxdb-verifications:wait', { verificationRunId }),
  cancelBackupInfluxDbVerification: (verificationRunId) => ipcRenderer.invoke('backup:influxdb-verifications:cancel', { verificationRunId }),
  approveBackupClickHouseDestination: (id, diskName, confirmationText) => ipcRenderer.invoke('backup:connections:clickhouse:approve-destination', { id, diskName, confirmationText }),
  previewBackupClickHouseRestore: (payload) => ipcRenderer.invoke('backup:clickhouse-restores:preview', payload),
  listBackupClickHouseRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:clickhouse-restores:list', payload),
  startBackupClickHouseRestore: (payload) => ipcRenderer.invoke('backup:clickhouse-restores:start', payload),
  waitBackupClickHouseRestore: (restoreRunId) => ipcRenderer.invoke('backup:clickhouse-restores:wait', { restoreRunId }),
  cancelBackupClickHouseRestore: (restoreRunId) => ipcRenderer.invoke('backup:clickhouse-restores:cancel', { restoreRunId }),
  listBackupClickHouseVerificationRuns: (payload = {}) => ipcRenderer.invoke('backup:clickhouse-verifications:list', payload),
  startBackupClickHouseVerification: (payload) => ipcRenderer.invoke('backup:clickhouse-verifications:start', payload),
  waitBackupClickHouseVerification: (verificationRunId) => ipcRenderer.invoke('backup:clickhouse-verifications:wait', { verificationRunId }),
  cancelBackupClickHouseVerification: (verificationRunId) => ipcRenderer.invoke('backup:clickhouse-verifications:cancel', { verificationRunId }),
  previewBackupNeo4jRestore: (payload) => ipcRenderer.invoke('backup:neo4j-restores:preview', payload),
  listBackupNeo4jRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:neo4j-restores:list', payload),
  startBackupNeo4jRestore: (payload) => ipcRenderer.invoke('backup:neo4j-restores:start', payload),
  waitBackupNeo4jRestore: (restoreRunId) => ipcRenderer.invoke('backup:neo4j-restores:wait', { restoreRunId }),
  cancelBackupNeo4jRestore: (restoreRunId) => ipcRenderer.invoke('backup:neo4j-restores:cancel', { restoreRunId }),
  listBackupNeo4jVerificationRuns: (payload = {}) => ipcRenderer.invoke('backup:neo4j-verifications:list', payload),
  startBackupNeo4jVerification: (payload) => ipcRenderer.invoke('backup:neo4j-verifications:start', payload),
  waitBackupNeo4jVerification: (verificationRunId) => ipcRenderer.invoke('backup:neo4j-verifications:wait', { verificationRunId }),
  cancelBackupNeo4jVerification: (verificationRunId) => ipcRenderer.invoke('backup:neo4j-verifications:cancel', { verificationRunId }),
  previewBackupNeo4jAggregation: (payload) => ipcRenderer.invoke('backup:neo4j-aggregations:preview', payload),
  listBackupNeo4jAggregationRuns: (payload = {}) => ipcRenderer.invoke('backup:neo4j-aggregations:list', payload),
  startBackupNeo4jAggregation: (payload) => ipcRenderer.invoke('backup:neo4j-aggregations:start', payload),
  waitBackupNeo4jAggregation: (runId) => ipcRenderer.invoke('backup:neo4j-aggregations:wait', { runId }),
  cancelBackupNeo4jAggregation: (runId) => ipcRenderer.invoke('backup:neo4j-aggregations:cancel', { runId }),
  listBackupCassandraScyllaConnections: () => ipcRenderer.invoke('backup:connections:cassandra-scylla:list'),
  createBackupCassandraScyllaConnection: (payload) => ipcRenderer.invoke('backup:connections:cassandra-scylla:create', payload),
  testBackupCassandraScyllaConnection: (id) => ipcRenderer.invoke('backup:connections:cassandra-scylla:test', { id }),
  discoverBackupCassandraScyllaResources: (id, kind = 'all') => ipcRenderer.invoke('backup:connections:cassandra-scylla:discover', { id, kind }),
  previewBackupCassandraScyllaRestore: (payload) => ipcRenderer.invoke('backup:cassandra-scylla-restores:preview', payload),
  listBackupCassandraScyllaRestoreRuns: (payload) => ipcRenderer.invoke('backup:cassandra-scylla-restores:list', payload),
  startBackupCassandraScyllaRestore: (payload) => ipcRenderer.invoke('backup:cassandra-scylla-restores:start', payload),
  waitBackupCassandraScyllaRestore: (restoreRunId) => ipcRenderer.invoke('backup:cassandra-scylla-restores:wait', { restoreRunId }),
  cancelBackupCassandraScyllaRestore: (restoreRunId) => ipcRenderer.invoke('backup:cassandra-scylla-restores:cancel', { restoreRunId }),
  listBackupScyllaManagerConnections: () => ipcRenderer.invoke('backup:connections:scylla-manager:list'),
  createBackupScyllaManagerConnection: (payload) => ipcRenderer.invoke('backup:connections:scylla-manager:create', payload),
  testBackupScyllaManagerConnection: (id) => ipcRenderer.invoke('backup:connections:scylla-manager:test', { id }),
  discoverBackupScyllaManagerResources: (id, kind = 'all') => ipcRenderer.invoke('backup:connections:scylla-manager:discover', { id, kind }),
  verifyBackupScyllaManagerTarget: (id, taskUpdate) => ipcRenderer.invoke('backup:connections:scylla-manager:verify-target', { id, taskUpdate }),
  listBackupScyllaManagerTasks: (payload) => ipcRenderer.invoke('backup:scylla-manager:tasks:list', payload),
  startBackupScyllaManagerTask: (payload) => ipcRenderer.invoke('backup:scylla-manager:tasks:start', payload),
  stopBackupScyllaManagerTask: (payload) => ipcRenderer.invoke('backup:scylla-manager:tasks:stop', payload),
  getBackupScyllaManagerTaskHistory: (payload) => ipcRenderer.invoke('backup:scylla-manager:tasks:history', payload),
  getBackupScyllaManagerTaskProgress: (payload) => ipcRenderer.invoke('backup:scylla-manager:tasks:progress', payload),
  listBackupScyllaManagerBackups: (payload) => ipcRenderer.invoke('backup:scylla-manager:backups:list', payload),
  previewBackupScyllaManagerRestore: (payload) => ipcRenderer.invoke('backup:scylla-manager-restores:preview', payload),
  listBackupScyllaManagerRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:scylla-manager-restores:list', payload),
  startBackupScyllaManagerRestore: (payload) => ipcRenderer.invoke('backup:scylla-manager-restores:start', payload),
  waitBackupScyllaManagerRestore: (restoreRunId) => ipcRenderer.invoke('backup:scylla-manager-restores:wait', { restoreRunId }),
  cancelBackupScyllaManagerRestore: (restoreRunId) => ipcRenderer.invoke('backup:scylla-manager-restores:cancel', { restoreRunId }),
  listBackupScyllaManagerVerificationRuns: (payload = {}) => ipcRenderer.invoke('backup:scylla-manager-verifications:list', payload),
  startBackupScyllaManagerVerification: (payload) => ipcRenderer.invoke('backup:scylla-manager-verifications:start', payload),
  waitBackupScyllaManagerVerification: (verificationRunId) => ipcRenderer.invoke('backup:scylla-manager-verifications:wait', { verificationRunId }),
  cancelBackupScyllaManagerVerification: (verificationRunId) => ipcRenderer.invoke('backup:scylla-manager-verifications:cancel', { verificationRunId }),
  listBackupSearchSnapshotConnections: () => ipcRenderer.invoke('backup:connections:search-snapshot:list'),
  createBackupSearchSnapshotConnection: (payload) => ipcRenderer.invoke('backup:connections:search-snapshot:create', payload),
  testBackupSearchSnapshotConnection: (id) => ipcRenderer.invoke('backup:connections:search-snapshot:test', { id }),
  verifyBackupSearchSnapshotRepository: (id, repositoryName) => ipcRenderer.invoke('backup:connections:search-snapshot:verify-repository', { id, repositoryName }),
  discoverBackupSearchSnapshotResources: (id, kind = 'repositories') => ipcRenderer.invoke('backup:connections:search-snapshot:discover', { id, kind }),
  previewBackupSearchSnapshotRestore: (payload) => ipcRenderer.invoke('backup:search-snapshot-restores:preview', payload),
  listBackupSearchSnapshotRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:search-snapshot-restores:list', payload),
  startBackupSearchSnapshotRestore: (payload) => ipcRenderer.invoke('backup:search-snapshot-restores:start', payload),
  waitBackupSearchSnapshotRestore: (restoreRunId) => ipcRenderer.invoke('backup:search-snapshot-restores:wait', { restoreRunId }),
  cancelBackupSearchSnapshotRestore: (restoreRunId) => ipcRenderer.invoke('backup:search-snapshot-restores:cancel', { restoreRunId }),
  planBackupSearchSnapshotRetention: (recoveryPointId) => ipcRenderer.invoke('backup:search-snapshot-retention:plan', { recoveryPointId }),
  executeBackupSearchSnapshotRetention: (recoveryPointId, planId) => ipcRenderer.invoke('backup:search-snapshot-retention:execute', { recoveryPointId, planId }),
  cleanupBackupSearchSnapshotRepository: (payload) => ipcRenderer.invoke('backup:search-snapshot-repositories:cleanup', payload),
  listBackupSearchSnapshotVerificationRuns: (payload = {}) => ipcRenderer.invoke('backup:search-snapshot-verifications:list', payload),
  startBackupSearchSnapshotVerification: (payload) => ipcRenderer.invoke('backup:search-snapshot-verifications:start', payload),
  waitBackupSearchSnapshotVerification: (verificationRunId) => ipcRenderer.invoke('backup:search-snapshot-verifications:wait', { verificationRunId }),
  cancelBackupSearchSnapshotVerification: (verificationRunId) => ipcRenderer.invoke('backup:search-snapshot-verifications:cancel', { verificationRunId }),
  listBackupSqliteConnections: () => ipcRenderer.invoke('backup:connections:sqlite:list'),
  createBackupSqliteConnection: (payload) => ipcRenderer.invoke('backup:connections:sqlite:create', payload),
  testBackupSqliteConnection: (id) => ipcRenderer.invoke('backup:connections:sqlite:test', { id }),
  discoverBackupSqliteDatabases: (id, payload = {}) => ipcRenderer.invoke('backup:connections:sqlite:discover', { id, ...payload }),
  listBackupFileSources: (connectionId) => ipcRenderer.invoke('backup:file-sources:list', { connectionId }),
  saveBackupFileSource: (payload) => ipcRenderer.invoke('backup:file-sources:save', payload),
  deleteBackupFileSource: (id, revision) => ipcRenderer.invoke('backup:file-sources:delete', { id, revision }),
  listBackupDatabaseAdapters: () => ipcRenderer.invoke('backup:database-adapters:list'),
  listBackupDatabaseSources: (connectionId) => ipcRenderer.invoke('backup:database-sources:list', { connectionId }),
  saveBackupDatabaseSource: (payload) => ipcRenderer.invoke('backup:database-sources:save', payload),
  deleteBackupDatabaseSource: (id, revision) => ipcRenderer.invoke('backup:database-sources:delete', { id, revision }),
  getBackupJobReadiness: () => ipcRenderer.invoke('backup:jobs:readiness'),
  listBackupJobs: () => ipcRenderer.invoke('backup:jobs:list'),
  getBackupObjectiveStatus: () => ipcRenderer.invoke('backup:objectives:status'),
  createBackupJob: (payload) => ipcRenderer.invoke('backup:jobs:create', payload),
  pauseBackupJob: (id, revision) => ipcRenderer.invoke('backup:jobs:pause', { id, revision }),
  resumeBackupJob: (id, revision) => ipcRenderer.invoke('backup:jobs:resume', { id, revision }),
  cloneBackupJob: (id, revision, name) => ipcRenderer.invoke('backup:jobs:clone', { id, revision, name }),
  disableBackupJob: (id, revision) => ipcRenderer.invoke('backup:jobs:disable', { id, revision }),
  deleteBackupJob: (id, revision) => ipcRenderer.invoke('backup:jobs:delete', { id, revision }),
  listBackupRuns: (payload = {}) => ipcRenderer.invoke('backup:jobs:runs:list', payload),
  runBackupJob: (jobId) => ipcRenderer.invoke('backup:jobs:run', { jobId }),
  resumeBackupRun: (runId) => ipcRenderer.invoke('backup:runs:resume', { runId }),
  cancelBackupRun: (runId) => ipcRenderer.invoke('backup:runs:cancel', { runId }),
  retryBackupRun: (runId) => ipcRenderer.invoke('backup:runs:retry', { runId }),
  getBackupWorkerStatus: () => ipcRenderer.invoke('backup:worker:status'),
  listBackupRecoveryPoints: (payload = {}) => ipcRenderer.invoke('backup:recovery-points:list', payload),
  browseBackupSnapshot: (payload) => ipcRenderer.invoke('backup:snapshots:browse', payload),
  searchBackupSnapshot: (payload) => ipcRenderer.invoke('backup:snapshots:search', payload),
  listBackupFileVersions: (payload) => ipcRenderer.invoke('backup:snapshots:file-versions', payload),
  listBackupRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:restores:list', payload),
  startBackupFileRestore: (payload) => ipcRenderer.invoke('backup:restores:start', payload),
  waitBackupFileRestore: (restoreRunId) => ipcRenderer.invoke('backup:restores:wait', { restoreRunId }),
  listBackupMysqlRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:mysql-restores:list', payload),
  startBackupMysqlRestore: (payload) => ipcRenderer.invoke('backup:mysql-restores:start', payload),
  waitBackupMysqlRestore: (restoreRunId) => ipcRenderer.invoke('backup:mysql-restores:wait', { restoreRunId }),
  listBackupMysqlPhysicalRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:mysql-physical-restores:list', payload),
  startBackupMysqlPhysicalRestore: (payload) => ipcRenderer.invoke('backup:mysql-physical-restores:start', payload),
  waitBackupMysqlPhysicalRestore: (restoreRunId) => ipcRenderer.invoke('backup:mysql-physical-restores:wait', { restoreRunId }),
  cancelBackupMysqlPhysicalRestore: (restoreRunId) => ipcRenderer.invoke('backup:mysql-physical-restores:cancel', { restoreRunId }),
  listBackupMariadbRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:mariadb-restores:list', payload),
  startBackupMariadbRestore: (payload) => ipcRenderer.invoke('backup:mariadb-restores:start', payload),
  waitBackupMariadbRestore: (restoreRunId) => ipcRenderer.invoke('backup:mariadb-restores:wait', { restoreRunId }),
  listBackupMysqlPitrRuns: (payload = {}) => ipcRenderer.invoke('backup:mysql-pitr:list', payload),
  startBackupMysqlPitr: (payload) => ipcRenderer.invoke('backup:mysql-pitr:start', payload),
  waitBackupMysqlPitr: (restoreRunId) => ipcRenderer.invoke('backup:mysql-pitr:wait', { restoreRunId }),
  listBackupMariadbPitrRuns: (payload = {}) => ipcRenderer.invoke('backup:mariadb-pitr:list', payload),
  startBackupMariadbPitr: (payload) => ipcRenderer.invoke('backup:mariadb-pitr:start', payload),
  waitBackupMariadbPitr: (restoreRunId) => ipcRenderer.invoke('backup:mariadb-pitr:wait', { restoreRunId }),
  listBackupPostgresqlRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:postgresql-restores:list', payload),
  startBackupPostgresqlRestore: (payload) => ipcRenderer.invoke('backup:postgresql-restores:start', payload),
  waitBackupPostgresqlRestore: (restoreRunId) => ipcRenderer.invoke('backup:postgresql-restores:wait', { restoreRunId }),
  listBackupPostgresqlPitrRuns: (payload = {}) => ipcRenderer.invoke('backup:postgresql-pitr:list', payload),
  startBackupPostgresqlPitr: (payload) => ipcRenderer.invoke('backup:postgresql-pitr:start', payload),
  waitBackupPostgresqlPitr: (restoreRunId) => ipcRenderer.invoke('backup:postgresql-pitr:wait', { restoreRunId }),
  cancelBackupPostgresqlPitr: (restoreRunId) => ipcRenderer.invoke('backup:postgresql-pitr:cancel', { restoreRunId }),
  listBackupSqlServerRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:sqlserver-restores:list', payload),
  startBackupSqlServerRestore: (payload) => ipcRenderer.invoke('backup:sqlserver-restores:start', payload),
  waitBackupSqlServerRestore: (restoreRunId) => ipcRenderer.invoke('backup:sqlserver-restores:wait', { restoreRunId }),
  cancelBackupSqlServerRestore: (restoreRunId) => ipcRenderer.invoke('backup:sqlserver-restores:cancel', { restoreRunId }),
  listBackupOracleRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:oracle-restores:list', payload),
  startBackupOracleRestore: (payload) => ipcRenderer.invoke('backup:oracle-restores:start', payload),
  waitBackupOracleRestore: (restoreRunId) => ipcRenderer.invoke('backup:oracle-restores:wait', { restoreRunId }),
  cancelBackupOracleRestore: (restoreRunId) => ipcRenderer.invoke('backup:oracle-restores:cancel', { restoreRunId }),
  listBackupMongoDbRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:mongodb-restores:list', payload),
  startBackupMongoDbRestore: (payload) => ipcRenderer.invoke('backup:mongodb-restores:start', payload),
  waitBackupMongoDbRestore: (restoreRunId) => ipcRenderer.invoke('backup:mongodb-restores:wait', { restoreRunId }),
  cancelBackupMongoDbRestore: (restoreRunId) => ipcRenderer.invoke('backup:mongodb-restores:cancel', { restoreRunId }),
  listBackupRedisRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:redis-restores:list', payload),
  startBackupRedisRestore: (payload) => ipcRenderer.invoke('backup:redis-restores:start', payload),
  waitBackupRedisRestore: (restoreRunId) => ipcRenderer.invoke('backup:redis-restores:wait', { restoreRunId }),
  cancelBackupRedisRestore: (restoreRunId) => ipcRenderer.invoke('backup:redis-restores:cancel', { restoreRunId }),
  listBackupSqliteRestoreRuns: (payload = {}) => ipcRenderer.invoke('backup:sqlite-restores:list', payload),
  startBackupSqliteRestore: (payload) => ipcRenderer.invoke('backup:sqlite-restores:start', payload),
  waitBackupSqliteRestore: (restoreRunId) => ipcRenderer.invoke('backup:sqlite-restores:wait', { restoreRunId }),
  cancelBackupSqliteRestore: (restoreRunId) => ipcRenderer.invoke('backup:sqlite-restores:cancel', { restoreRunId }),
  listBackupVerificationRuns: (payload = {}) => ipcRenderer.invoke('backup:verifications:list', payload),
  startBackupVerification: (payload) => ipcRenderer.invoke('backup:verifications:start', payload),
  waitBackupVerification: (verificationRunId) => ipcRenderer.invoke('backup:verifications:wait', { verificationRunId }),
  listBackupLogs: (payload = {}) => ipcRenderer.invoke('backup:logs:list', payload),
  listBackupNotificationRoutes: () => ipcRenderer.invoke('backup:notifications:routes:list'),
  createBackupNotificationRoute: (payload) => ipcRenderer.invoke('backup:notifications:routes:create', payload),
  updateBackupNotificationRoute: (payload) => ipcRenderer.invoke('backup:notifications:routes:update', payload),
  deleteBackupNotificationRoute: (id, revision) => ipcRenderer.invoke('backup:notifications:routes:delete', { id, revision }),
  testBackupNotificationRoute: (id) => ipcRenderer.invoke('backup:notifications:routes:test', { id }),
  listBackupNotificationDeliveries: (payload = {}) => ipcRenderer.invoke('backup:notifications:deliveries:list', payload),
  listBackupLocalRepositories: () => ipcRenderer.invoke('backup:repositories:local:list'),
  testBackupLocalRepository: (id) => ipcRenderer.invoke('backup:repositories:local:test', { id }),
  createBackupLocalRepository: (payload) => ipcRenderer.invoke('backup:repositories:local:create', payload),
  deleteBackupLocalRepository: (id, revision) => ipcRenderer.invoke('backup:repositories:local:delete', { id, revision }),
  listBackupSftpRepositories: () => ipcRenderer.invoke('backup:repositories:sftp:list'),
  testBackupSftpRepository: (id) => ipcRenderer.invoke('backup:repositories:sftp:test', { id }),
  createBackupSftpRepository: (payload) => ipcRenderer.invoke('backup:repositories:sftp:create', payload),
  deleteBackupSftpRepository: (id, revision) => ipcRenderer.invoke('backup:repositories:sftp:delete', { id, revision }),
  listBackupS3Repositories: () => ipcRenderer.invoke('backup:repositories:s3:list'),
  testBackupS3Repository: (id) => ipcRenderer.invoke('backup:repositories:s3:test', { id }),
  createBackupS3Repository: (payload) => ipcRenderer.invoke('backup:repositories:s3:create', payload),
  deleteBackupS3Repository: (id, revision) => ipcRenderer.invoke('backup:repositories:s3:delete', { id, revision }),
  updateBackupRepositoryStoragePolicy: (payload) => ipcRenderer.invoke('backup:repositories:storage-policy:update', payload),
  planBackupRepositoryPrune: (repositoryId) => ipcRenderer.invoke('backup:repositories:prune-plan', { repositoryId }),
  pruneBackupRepository: (repositoryId, planId) => ipcRenderer.invoke('backup:repositories:prune', { repositoryId, planId }),
  saveTemplate: (template) => ipcRenderer.invoke('templates:save', template),
  deleteTemplate: (id) => ipcRenderer.invoke('templates:delete', id),
  exportTemplates: (templateIds) => ipcRenderer.invoke('templates:export', templateIds),
  importTemplates: () => ipcRenderer.invoke('templates:import'),
  selectKey: () => ipcRenderer.invoke('dialog:select-key'),
  selectUpload: () => ipcRenderer.invoke('dialog:select-upload'),
  selectFtpUpload: () => ipcRenderer.invoke('dialog:select-ftp-upload'),
  selectFtpDownload: (defaultName) => ipcRenderer.invoke('dialog:select-ftp-download', defaultName),
  selectTerminalDownload: (defaultName) => ipcRenderer.invoke('dialog:select-terminal-download', defaultName),
  selectLocalFolder: (defaultPath) => ipcRenderer.invoke('dialog:select-local-folder', defaultPath),
  getPathForDroppedFile: (file) => {
    try {
      return file?.path || webUtils.getPathForFile(file) || '';
    } catch {
      return '';
    }
  },
  runDeployment: (payload) => ipcRenderer.invoke('deployment:run', payload),
  stopDeployment: (runId) => ipcRenderer.invoke('deployment:stop', runId),
  startTerminal: (payload) => ipcRenderer.invoke('terminal:start', payload),
  startServerMonitoring: (payload) => ipcRenderer.invoke('server-monitoring:start', payload),
  pauseServerMonitoring: (sessionId, paused) => ipcRenderer.invoke('server-monitoring:pause', { sessionId, paused }),
  stopServerMonitoring: (sessionId) => ipcRenderer.invoke('server-monitoring:stop', sessionId),
  getTerminalHomeDirectory: (sessionId) => ipcRenderer.invoke('terminal:home-directory', sessionId),
  listTerminalDirectory: (payload) => ipcRenderer.invoke('terminal:list-directory', payload),
  readTerminalFile: (payload) => ipcRenderer.invoke('terminal:read-file', payload),
  writeTerminalFile: (payload) => ipcRenderer.invoke('terminal:write-file', payload),
  downloadTerminalFile: (payload) => ipcRenderer.invoke('terminal:download', payload),
  downloadTerminalEntryToDirectory: (payload) => ipcRenderer.invoke('terminal:download-to-directory', payload),
  makeTerminalDirectory: (payload) => ipcRenderer.invoke('terminal:mkdir', payload),
  renameTerminalEntry: (payload) => ipcRenderer.invoke('terminal:rename', payload),
  openTerminalEntryWith: (payload) => ipcRenderer.invoke('terminal:open-with', payload),
  deleteTerminalEntry: (payload) => ipcRenderer.invoke('terminal:delete', payload),
  uploadTerminalFile: (payload) => ipcRenderer.invoke('terminal:upload', payload),
  cancelTerminalUpload: (sessionId) => ipcRenderer.invoke('terminal:upload-cancel', sessionId),
  sendTerminalInput: (payload) => ipcRenderer.send('terminal:input:send', payload),
  resizeTerminal: (payload) => ipcRenderer.invoke('terminal:resize', payload),
  stopTerminal: (sessionId) => ipcRenderer.invoke('terminal:stop', sessionId),
  localList: (payload) => ipcRenderer.invoke('local:list', payload),
  getProjectLocalSettings: (projectId) => ipcRenderer.invoke('project-local-settings:get', projectId),
  setProjectLocalSettings: (projectId, settings) => ipcRenderer.invoke('project-local-settings:set', projectId, settings),
  deleteProjectLocalSettings: (projectId) => ipcRenderer.invoke('project-local-settings:delete', projectId),
  listUptimeMonitors: (options = {}) => invokeUptime('uptime:monitors:list', options),
  getUptimeMonitor: (id) => invokeUptime('uptime:monitors:get', { id }),
  createUptimeMonitor: (payload) => invokeUptime('uptime:monitors:create', payload),
  updateUptimeMonitor: (payload) => invokeUptime('uptime:monitors:update', payload),
  deleteUptimeMonitor: (id, revision) => invokeUptime('uptime:monitors:delete', { id, revision }),
  testUptimeMonitor: (payload) => invokeUptime('uptime:monitors:test', payload),
  runUptimeMonitorNow: (id) => invokeUptime('uptime:monitors:run-now', { id }),
  listUptimeChecks: (payload) => invokeUptime('uptime:checks:list', payload),
  listUptimeIncidents: (options = {}) => invokeUptime('uptime:incidents:list', options),
  acknowledgeUptimeIncident: (id, revision, note = '') => invokeUptime('uptime:incidents:acknowledge', { id, revision, note }),
  listUptimeMaintenance: (options = {}) => invokeUptime('uptime:maintenance:list', options),
  createUptimeMaintenance: (payload) => invokeUptime('uptime:maintenance:create', payload),
  updateUptimeMaintenance: (payload) => invokeUptime('uptime:maintenance:update', payload),
  deleteUptimeMaintenance: (id, revision) => invokeUptime('uptime:maintenance:delete', { id, revision }),
  getUptimeWorkerStatus: () => invokeUptime('uptime:worker:status'),
  getUptimeMonitoringSettings: () => invokeUptime('uptime:settings:get'),
  updateUptimeMonitoringSettings: (payload) => invokeUptime('uptime:settings:update', payload),
  getUptimeReport: (options = {}) => invokeUptime('uptime:reports:get', options),
  exportUptimeCsv: (options = {}) => invokeUptime('uptime:reports:export-csv', options),
  exportUptimePdf: (options = {}) => invokeUptime('uptime:reports:export-pdf', options),
  getUptimeProjectState: (projectId) => ipcRenderer.invoke('uptime:getProjectState', projectId),
  getUptimeMonitorHistory: (payload) => ipcRenderer.invoke('uptime:getMonitorHistory', payload),
  getUptimeServiceStatus: () => ipcRenderer.invoke('uptime:getServiceStatus'),
  runUptimeNow: (payload) => ipcRenderer.invoke('uptime:runNow', payload),
  localOpen: (payload) => ipcRenderer.invoke('local:open', payload),
  localOpenWith: (payload) => ipcRenderer.invoke('local:open-with', payload),
  localMkdir: (payload) => ipcRenderer.invoke('local:mkdir', payload),
  localRename: (payload) => ipcRenderer.invoke('local:rename', payload),
  localDelete: (payload) => ipcRenderer.invoke('local:delete', payload),
  ftpConnect: (payload) => ipcRenderer.invoke('ftp:connect', payload),
  ftpList: (payload) => ipcRenderer.invoke('ftp:list', payload),
  ftpUpload: (payload) => ipcRenderer.invoke('ftp:upload', payload),
  ftpDownload: (payload) => ipcRenderer.invoke('ftp:download', payload),
  ftpDownloadToDirectory: (payload) => ipcRenderer.invoke('ftp:download-to-directory', payload),
  ftpOpen: (payload) => ipcRenderer.invoke('ftp:open', payload),
  ftpOpenWith: (payload) => ipcRenderer.invoke('ftp:open-with', payload),
  ftpMkdir: (payload) => ipcRenderer.invoke('ftp:mkdir', payload),
  ftpRename: (payload) => ipcRenderer.invoke('ftp:rename', payload),
  ftpDelete: (payload) => ipcRenderer.invoke('ftp:delete', payload),
  ftpDisconnect: (sessionId) => ipcRenderer.invoke('ftp:disconnect', sessionId),
  emergencyStop: () => ipcRenderer.invoke('emergency:stop'),
  resolveConfirmation: (payload) => ipcRenderer.invoke('ui:confirm-response', payload),
  onConfirmationRequest: (callback) => {
    const handler = (_event, message) => callback(message);
    ipcRenderer.on('ui:confirm-request', handler);
    return () => ipcRenderer.removeListener('ui:confirm-request', handler);
  },
  onAppUpdateEvent: (callback) => {
    const handler = (_event, message) => callback(message);
    ipcRenderer.on('app:update-event', handler);
    return () => ipcRenderer.removeListener('app:update-event', handler);
  },
  onDeploymentEvent: (callback) => {
    const handler = (_event, message) => callback(message);
    ipcRenderer.on('deployment:event', handler);
    return () => ipcRenderer.removeListener('deployment:event', handler);
  },
  onTerminalEvent: (callback) => {
    const handler = (_event, message) => callback(message);
    ipcRenderer.on('terminal:event', handler);
    return () => ipcRenderer.removeListener('terminal:event', handler);
  },
  onServerMonitoringEvent: (callback) => {
    const handler = (_event, message) => callback(message);
    ipcRenderer.on('server-monitoring:event', handler);
    return () => ipcRenderer.removeListener('server-monitoring:event', handler);
  },
  onRdpEvent: (callback) => {
    const handler = (_event, message) => callback(message);
    ipcRenderer.on('rdp:event', handler);
    return () => ipcRenderer.removeListener('rdp:event', handler);
  },
  onRdpFullscreenChanged: (callback) => {
    const handler = (_event, enabled) => callback(Boolean(enabled));
    ipcRenderer.on('rdp:fullscreen-changed', handler);
    return () => ipcRenderer.removeListener('rdp:fullscreen-changed', handler);
  },
  onUptimeEvent: (callback) => {
    const handler = (_event, message) => callback(message);
    ipcRenderer.on('uptime:event', handler);
    return () => ipcRenderer.removeListener('uptime:event', handler);
  },
  onUptimeNavigate: (callback) => {
    const handler = (_event, target) => callback(target);
    ipcRenderer.on('uptime:navigate', handler);
    return () => ipcRenderer.removeListener('uptime:navigate', handler);
  },
  onDatabaseManagerEvent: (callback) => {
    if (typeof callback !== 'function') throw new TypeError('Database Manager event callback is invalid.');
    const handler = (_event, message) => {
      if (message?.databaseManagerEventVersion === DATABASE_MANAGER_EVENT_VERSION) callback(message);
    };
    ipcRenderer.on('database-manager:event', handler);
    return () => ipcRenderer.removeListener('database-manager:event', handler);
  }
});
